apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
      - name: pacman
        image: rwaltertcd/pacman:latest
        ports:
        - containerPort: 80
        env:
        - name: MONGO_USERNAME
          value: "<MONGO_USERNAME>"
        - name: MONGO_PASSWORD
          value: "<"MONGO_PASSWORD>"
        - name: REDIS_HOST
          value: "redis-master.redis.svc.cluster.local"
        - name: REDIS_PASSWORD
          value: "<REDIS_PASSWORD>"
        
